/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error": "#ba1a1a",
        "secondary-fixed-dim": "#b9c6eb",
        "surface-container": "#ebeef0",
        "tertiary-fixed-dim": "#ffb86e",
        "background": "#f7fafc",
        "on-secondary-container": "#525f7f",
        "on-primary-fixed-variant": "#004881",
        "tertiary": "#784600",
        "primary": "#005394",
        "surface-dim": "#d7dadc",
        "on-tertiary-container": "#ffe7d2",
        "on-background": "#181c1e",
        "surface-tint": "#1960a3",
        "surface-container-low": "#f1f4f6",
        "on-primary-fixed": "#001c38",
        "inverse-primary": "#a2c9ff",
        "surface-container-high": "#e5e9eb",
        "outline-variant": "#c1c7d2",
        "primary-fixed-dim": "#a2c9ff",
        "primary-container": "#2b6cb0",
        "primary-fixed": "#d3e4ff",
        "inverse-surface": "#2d3133",
        "on-primary": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#3a4665",
        "surface-variant": "#e0e3e5",
        "inverse-on-surface": "#eef1f3",
        "on-error-container": "#93000a",
        "on-primary-container": "#e1ecff",
        "surface-bright": "#f7fafc",
        "on-error": "#ffffff",
        "outline": "#727782",
        "on-secondary-fixed": "#0d1b37",
        "secondary": "#515e7e",
        "on-surface": "#181c1e",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#d9e2ff",
        "surface": "#f7fafc",
        "surface-container-highest": "#e0e3e5",
        "tertiary-fixed": "#ffdcbd",
        "on-tertiary-fixed": "#2c1600",
        "on-tertiary-fixed-variant": "#693c00",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#414750",
        "tertiary-container": "#9a5b00",
        "error-container": "#ffdad6",
        "secondary-container": "#cdd9ff",
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
